### ISSUE TITLE
about rust-rgb20

### ISSUE THREAD

**Issue by cymqqqq** [RGB-Tools/rgb-lightning-sample#8]
Hi there, I found that in 97a1dc895f1e4140038dac8dd8298b304f0ab29e, there is a rust-rgb20 module, so do you have integrated rust-rgb20 with the rgb-lightning-sample?

**Comment by nicbus** [comment]
The `97a1dc8` commit is part of an older version of the project that used RGB v0.9. The project has since been updated to use RGB v0.10, where `rust-rgb20` is no longer needed.

That being said, the project supports NIA assets (NIA schema, from the RGB20 specification).

Also, please note that this project is being archived in favor of `rgb-lightning-node`
